### ISSUE TITLE
Description/details for about us section

### ISSUE THREAD

**Issue by seanc** [JustDame/Assignment6_Positive_Projection#12]
For the about us section, each of us will need to write some details about ourselves. This information sould be included here for whoever is working on the About Us section. So if @Jordane-Allen, @Athora190, and @JustDame when you are available, please comment here with:

Your name
A small description about you. Don't worry about it being accurate or super descriptive. Anything works!
And a picture you'd like to use for you.

**Comment by JustDame** [comment]
My name is Damian Pascal. I have had a variety of customer service opportunities, through which I was able to have fewer returns products and increased repeat customers. People find me to be an upbeat, self-motivated team player with excellent communication skills. ![image](https://user-images.githubusercontent.com/76237934/104398710-4847a700-551d-11eb-9769-598ccd63806f.jpeg)

**Comment by Jordane-Allen** [comment]
![blake-richard-verdoorn-cssvEZacHvQ-unsplash](https://user-images.githubusercontent.com/37087704/104537429-f6b81e80-55e7-11eb-9075-49931c40a67a.jpg)
 Jordane Allen
Motivated student extraordinaire who likes to engage in enjoyable, meaningful and uplifting activities.

**Comment by Jade-Marte** [comment]
Jade Marte
A hard-working student who is willing to learn new things. And willing to help others along the way.
![abd1b2bc1d528e3e39dafb38be78ed30 (2)](https://user-images.githubusercontent.com/31541871/104497022-c2247280-55a7-11eb-9ac6-81425ce0559a.jpg)

**Comment by seanc** [comment]
Name: Sean Wilson-Bynoe
Description: 
I'm a full-stack web/software engineer working on FoxFiles software. I love to adventure into the unknown, whether that be some new topic or out and about mountain biking. I also like to play a variety of sports including tennis, soccer, badminton, and swimming. Often times, you'll find holed up in FoxFiles HQ working on new updates to our software. 

Role: Founder & Software Engineer

Image:
![image](https://user-images.githubusercontent.com/13725538/104537907-d76dc100-55e8-11eb-82af-84310ac74777.png)

**Comment by JustDame** [comment]
Completed changes to the description
