### ISSUE TITLE
Features section

### ISSUE THREAD

**Issue by seanc** [JustDame/Assignment6_Positive_Projection#3]
The features section should include a slide for each of our features along with a short description of each.

Our current features are:
- Save and upload files to your vault
- Upload your vault files to the cloud
- Convert common files in your vault to different formats
- Choose to compress your files in your vault to maximize cost 
- Remote access to your file vault
- Create files and folders
- Versioned files allowing you to see changes from years ago without losing valuable information

**Comment by Jade-Marte** [comment]
will be in assignment 8 with pages
