### ISSUE TITLE
Membership section

### ISSUE THREAD

**Issue by seanc** [JustDame/Assignment6_Positive_Projection#4]
The membership section should consist of a Plan component which might take in some props like `name`, `price`, and `description`

**Comment by seanc** [comment]
@JustDame I would suggest using `h3` for your section title component. You can do this by updating the h1 in the `variant` and `component` props on `Typography` to h3. This will make it the same size as the section title in @Jordane-Allen section.

**Comment by JustDame** [comment]
@seanc Closing this issue awaiting pull request approval.
