### ISSUE TITLE
Contact Form section

### ISSUE THREAD

**Issue by seanc** [JustDame/Assignment6_Positive_Projection#6]
The Contact Form section should contain a form with inputs like `name`, `email`, maybe a dropdown for `inquiry` with options like Sales, Business Inquiry, Technical Support, etc. and then a large textarea for main message. Then below that a button for submitting the form

**Comment by seanc** [comment]
Another suggestion that could be implemented later on is to layout the form in a way that utilizes more horizontal space. So maybe putting the input boxes for first name and last name on the same line, as well as email and phone number. Then textarea would have its own space occupying both of the columns at the bottom.

**Comment by Jordane-Allen** [comment]
I made the changes to the layout of the contact form and it should be okay now.
