### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by seanc** [JustDame/Assignment6_Positive_Projection#7]
Should contain something like "Copyright <company name> 2020"

**Comment by Jade-Marte** [comment]
I could do the footer and About us sections however, I might need some assistance

**Comment by JustDame** [comment]
@Athora190 The Copyright year should be 2021.

**Comment by Jade-Marte** [comment]
having trouble with the footer at the color and items are not cooperating

**Comment by Jade-Marte** [comment]
okay everything is working properly now
